### ISSUE TITLE
Dynamo.FromQueryIndex<T> with Contains causes AmazonDynamoDBException

### ISSUE THREAD

**Issue by strongeye** [ServiceStack/ServiceStack.Aws#5]
Source:
 results.AddRange(Dynamo.FromQueryIndex<ManagingAccountCardsGlobalIndex>(
                    x => rollupAccountList.Contains(x.ManagingAccountId)).Exec();

Invalid KeyConditionExpression: Syntax error; token: ")", near: "()"

Not certain if this is supported or not, but wanted to log it. The type of ManagingAccountId is long.

Exception detail follows
Amazon.DynamoDBv2.AmazonDynamoDBException was unhandled by user code
  ErrorCode=ValidationException
  HResult=-2146233088
  Message=Invalid KeyConditionExpression: Syntax error; token: ")", near: "()"
  RequestId=3110f430-77db-4392-a5f8-b2838a753b60
  Source=AWSSDK.Core
  StackTrace:
       at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 116
       at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
       at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 202
       at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 76
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 38
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 72
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 84
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointResolver.cs:line 34
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Marshaller.cs:line 37
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
       at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 135
       at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 118
       at Amazon.DynamoDBv2.AmazonDynamoDBClient.Query(QueryRequest request) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\_bcl45\AmazonDynamoDBClient.cs:line 3053
       at ServiceStack.Aws.DynamoDb.PocoDynamo.<>c__DisplayClass8e`1.<Query>b__8c()
       at ServiceStack.Aws.DynamoDb.PocoDynamo.Exec[T](Func`1 fn, Type[] rethrowExceptions, HashSet`1 retryOnErrorCodes)
       at ServiceStack.Aws.DynamoDb.PocoDynamo.<Query>d__90`1.MoveNext()
       at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
       at System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
       at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
       at Ui_Base.ServiceInterface.Cards.CardsService.Get(ListCardsRequest request) in C:\Trunk\starting_template\Ui_Base\Ui_Base\Ui_Base.ServiceInterface\Cards\CardsService.cs:line 51
       at lambda_method(Closure , Object , Object )
       at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto)
  InnerException: 
       HResult=-2146233088
       Message=The remote server returned an error: (400) Bad Request.
       Source=AWSSDK.Core
       StackTrace:
            at Amazon.Runtime.Internal.HttpRequest.GetResponse() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 114
            at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 84
            at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
            at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 48
            at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
            at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 70
       InnerException: 
            HResult=-2146233079
            Message=The remote server returned an error: (400) Bad Request.
            Source=System
            StackTrace:
                 at System.Net.HttpWebRequest.GetResponse()
                 at Amazon.Runtime.Internal.HttpRequest.GetResponse() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 106
            InnerException:

**Comment by mythz** [comment]
Hi, can you provide complete/working code so I can run the example locally?

**Comment by strongeye** [comment]
yes, will do momentarily if I am able to verify that this is not an error from my code.

**Comment by strongeye** [comment]
I am still working to get Contains to work, but this particular exception was because my collection was empty.

**Comment by strongeye** [comment]
My current issue (which is unrelated to initial exception) is giving this KeyConditionExpression IN exception

This post seems to indicate that KeyConditionExpression IN is not possible in a query operation
http://stackoverflow.com/questions/32671509/in-statement-in-dynamodb 
so right now I'm trying to work around this in another way. If there is any legitimate issue with this library, it might only be that it's not conveying what is possible to the user via meaningful exception messages. However, I understand that doing this would mean creating detailed layer of messages around all of the AWS features, which may not be a worthwhile exercise.

my code is attempting to use a List<long> of IDs to match the [HashKey] long value in a IGlobalIndex using Contains, and it's throwing the exception below. (right now it would be too difficult to package and share the code, so I'm trying to give the highlights in case it's of interest / useful)




More details
Amazon.DynamoDBv2.AmazonDynamoDBException was unhandled by user code
  ErrorCode=ValidationException
  HResult=-2146233088
  Message=Invalid operator used in KeyConditionExpression: IN
  RequestId=744c5539-7e3e-4cf4-a3e6-cac56f0ab56d
  Source=AWSSDK.Core
  StackTrace:
       at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 116
       at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
       at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 202
       at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 76
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 38
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 72
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 84
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointResolver.cs:line 34
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Marshaller.cs:line 37
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
       at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
       at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 135
       at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 118
       at Amazon.DynamoDBv2.AmazonDynamoDBClient.Query(QueryRequest request) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\_bcl45\AmazonDynamoDBClient.cs:line 3053
       at ServiceStack.Aws.DynamoDb.PocoDynamo.<>c__DisplayClass8e`1.<Query>b__8c()
       at ServiceStack.Aws.DynamoDb.PocoDynamo.Exec[T](Func`1 fn, Type[] rethrowExceptions, HashSet`1 retryOnErrorCodes)
       at ServiceStack.Aws.DynamoDb.PocoDynamo.<Query>d__90`1.MoveNext()
       at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
       at System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
       at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
       at Ui_Base.ServiceInterface.Cards.CardsService.Get(ListCardsRequest request) in C:\Trunk\starting_template\Ui_Base\Ui_Base\Ui_Base.ServiceInterface\Cards\CardsService.cs:line 59
       at lambda_method(Closure , Object , Object )
       at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto)
  InnerException: 
       HResult=-2146233088
       Message=The remote server returned an error: (400) Bad Request.
       Source=AWSSDK.Core
       StackTrace:
            at Amazon.Runtime.Internal.HttpRequest.GetResponse() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 114
            at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 84
            at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
            at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 48
            at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
            at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 70
       InnerException: 
            HResult=-2146233079
            Message=The remote server returned an error: (400) Bad Request.
            Source=System
            StackTrace:
                 at System.Net.HttpWebRequest.GetResponse()
                 at Amazon.Runtime.Internal.HttpRequest.GetResponse() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 106
            InnerException:
